cargo-features = ["trim-paths", "profile-rustflags"]

[package]
authors = ["Darius C", "Simon Bernier St-Pierre <sbernierstpierre@gmail.com>"]
description = "Internet Gateway Protocol client"
edition = "2021"
homepage = "https://github.com/dariusc93/rust-igd"
keywords = ["igd", "upnp", "tokio", "async-std"]
license = "MIT"
name = "igd-next"
readme = "README.md"
repository = "https://github.com/dariusc93/rust-igd"
version = "0.14.3"

[package.metadata.docs.rs]
all-features = true

[dependencies]
bytes = { version = "1", optional = true }
futures = { version = "0.3", optional = true }
http = { version = "0.2", optional = true }
log = "0.4"
rand = "0.8"
tokio = { version = "1", optional = true, features = ["net"] }
async-std = { version = "1", optional = true }
surf = { version = "2.3.2", optional = true, default-features = false }

url = "2"
xmltree = "0.10"
async-trait = { version = "0.1.72", optional = true }
minreq = "2.11.0"

[dependencies.hyper]
default-features = false
features = ["client", "http1", "http2", "runtime"]
optional = true
version = "0.14"

[dev-dependencies]
simplelog = "0.12"
tokio = { version = "1", features = ["full"] }
async-std = { version = "1", features = ["attributes"]}

[features]
aio_tokio = ["futures", "tokio", "hyper", "bytes", "http", "async-trait"]
aio_async_std = ["futures", "async-std", "surf/h1-client-rustls", "bytes", "http", "async-trait"]
default = []

[[example]]
name = "add_any_port"

[[example]]
name = "add_port"

[[example]]
name = "add_remove"

[[example]]
name = "aio_tokio"
required-features = ["aio_tokio"]

[[example]]
name = "aio_astd"
required-features = ["aio_async_std"]

[[example]]
name = "external_ip"

[[example]]
name = "remove_port"

[profile.release]
incremental = true
lto = "thin"
# strip = "debuginfo"
trim-paths = "all"
rustflags = ["-Zlocation-detail=none"]

[profile.min-size-release]
inherits = "release"
codegen-units = 1
lto = "fat"
opt-level = "s"

[profile.release-strip]
inherits = "release"
strip = "symbols"

[profile.min-size-release-strip]
inherits = "min-size-release"
strip = "symbols"
